name: Build Windows EXE
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: |
          pip install mss opencv-python numpy pyinstaller pillow soundcard soundfile
          pyinstaller --onefile --noconsole --name oko --icon=images.ico --add-data "images.ico;." --add-binary "ffmpeg.exe;." --hidden-import=soundcard --hidden-import=soundfile --collect-all soundcard --collect-all soundfile app.py
      - uses: actions/upload-artifact@v4
        with:
          name: oko-windows
          path: dist/oko.exe