- name: Build with PyInstaller
  run: pyinstaller --onefile --windowed --name="ScreenRecorder" --hidden-import=soundcard --hidden-import=soundcard.mediafoundation --hidden-import=cv2 --collect-submodules=cv2 --collect-submodules=soundcard --collect-data=soundcard --add-data "ffmpeg.exe;." app.py

- name: Prepare artifact
  run: copy ffmpeg.exe dist\ffmpeg.exe

- name: Upload artifact
  uses: actions/upload-artifact@v4
  with:
    name: ScreenRecorder-Windows
    path: |
      dist/ScreenRecorder.exe
      dist/ffmpeg.exe
